CC      =	gcc
FLAGS   =	-Wall -Werror -Wextra
RM      =	rm -rf
NAME    =   libft.a
OBJ     =   $(SRC:.c=.o)
BONUS_OBJ = $(BONUS_SRC:.c=.o)
SRC     =	ft_bzero.c ft_isalnum.c ft_isalpha.c ft_isascii.c ft_isdigit.c ft_isprint.c \
			ft_memchr.c ft_memcmp.c ft_memcpy.c ft_memmove.c ft_memset.c \
			ft_strlcat.c ft_strlcpy.c ft_strlen.c ft_strrchr.c ft_tolower.c ft_toupper.c ft_atoi.c \
			ft_strncmp.c ft_strnstr.c ft_strchr.c ft_strdup.c ft_substr.c ft_strjoin.c ft_calloc.c ft_split.c \
			ft_strtrim.c ft_itoa.c ft_strmapi.c ft_striteri.c ft_putchar_fd.c ft_putstr_fd.c ft_putendl_fd.c ft_putnbr_fd.c \
			ft_strlen_gnl.c ft_strchr_gnl.c ft_chr_bakn_gnl.c ft_new_line_gnl.c ft_str_attach_gnl.c ft_memmove_gnl.c \
			ft_memcpy_gnl.c get_next_line.c ft_exiting_prog.c

BONUS_SRC	=	ft_lstnew.c ft_lstadd_front.c ft_lstsize.c ft_lstlast.c ft_lstadd_back.c ft_lstdelone.c ft_lstclear.c \
				ft_lstiter.c ft_lstmap.c	


$(NAME): $(OBJ) $(BONUS_OBJ)
		ar -rcs $@ $^

bonus: $(BONUS_OBJ)
		ar -rcs ${NAME} $^ 

%.o : %.c
	$(CC) $(FLAGS) -c $^ -o $@	

all: $(NAME)

clean:
	$(RM) $(OBJ) $(BONUS_OBJ)

fclean: clean
	$(RM) $(NAME)

re: fclean all

.PHONY : all clean fclean re bonus